language: dart

dart: [1.24.3, stable, dev]

env:
  global:
    - LIBS="bin lib test"
  matrix:
    - TASK="dartanalyzer --fatal-warnings $LIBS analysis_options.yaml"
    - TASK="pub run test"
    # dartfmt is included below

matrix:
  #  fast_finish: true
  #  allow_failures:
  #    - dart: dev
  #      env: TASK="pub run test"
  include:
    - dart: stable
      env: TASK="dartfmt --set-exit-if-changed -n $LIBS"
  exclude:
    - dart: 1.24.3
      env: TASK="dartanalyzer --fatal-warnings $LIBS analysis_options.yaml"

script: $TASK

cache:
  directories:
    - $HOME/.pub-cache

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d(\.x|-dev)$/, /travis-build/]
