name: code_excerpt_updater
version: 0.16.0

description: Updates code excerpts inside markdown code blocks.

author: Patrice Chalin <pchalin@gmail.com>
homepage: https://github.com/chalin/code_excerpt_updater

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  args: '>=0.13.0 <2.0.0'
  logging: ^0.11.3+1
  path: ^1.4.0
  yaml: ^2.1.0

dev_dependencies:
  test: '>=0.12.33 <2.0.0'
  mockito: '>=2.2.2 <4.0.0'
